export const MSG_CONSTANT =  {
    slogan: 'Let’s create & edit images and videos...',
    login: {
      header: 'Hi, Genius!',
      subHeader: 'Let’s create something unique...',
      signInWith: 'Sign in with',
      forgotPassword: 'Forgot Password',
      createAccount: 'Create an Account',
      loginBtn: 'Login',
      loginFailed: 'Sorry, Your session has expired, please login again!'
    },
    singUp: {
      signupBtn: 'Sign Up',
      haveAccount: 'Already have an account? ',
    },
    inviteFromSocial: 'Invite Social Friends',
    about: 'About',
    sideDrawer: {
      terms: 'Terms & Conditions',
      privacy: 'Privacy Policy',
      private: 'Private Album',
      myFavorite: 'My Favorites',
      myFollowers: 'My Followers',
      myFollowings: 'My Followings',
      chat: 'Chat',
      profile: 'Profile',
      settings: 'Settings',
    },
    sharing: {
      byAddressBook: 'Share with Emails & Users',
      byQrCode: 'Share with QR Code',
      withOther: 'Share via...',
      qrTitle: 'MyZesty album',
      qrSubject: 'Checkout this awesome content',
    },
    actions: {
      album: {
        edit: 'Edit My Album',
        delete: 'Delete',
        report: 'Report',
        writeReportReason: 'Write your reason here...',
        reportReasonPlaceholder: 'I describe this post as',
        block: 'Block',
        unblock: 'Unblock',
        favorite: 'My Favorite',
        addMedia: 'Add more media',
        downloadMedia: 'Save Media to your Device',
        success: 'Success',
        downloadMsg: 'Album have been downloaded',
        qrMsg: 'QR code successfully downloaded'
      },
      albumShare: {
        facebook: 'Facebook',
        whatsapp: 'Whatsapp',
        whatsappStatus: 'Status',
        whatsappStories: 'Stories',
        instaStatus: 'Status',
        instaFeed: 'Feed',
        insta: 'Instagram',
        tiktok: 'Tiktok'
      },
      comment: {
        commentPlaceholder: 'Write your comment here...',
        replyPlaceholder: 'Write your reply here...',
      }
    },
    search: {
      noResult: 'Type a keyword in the search box...',
      noResult2: 'to search for Album names, Tags or Pictures',
    },
    chat: {
      searchPlaceholder: 'Search for a user...',
      noUserFound: 'Oops! no such user found',
      startConversation: ' Start a new conversation.',
      error: 'Error !!',
      msgFailed: 'You can not send message.',
      noChat: 'No Unread Chat.'
    },
    settings: {
      receiveNotifications: 'Receive notifications',
      receiveEmails: 'Receive emails',
      editProfile: 'Edit Profile',
      changePassword: 'Change Password',
      logout: 'Logout',
      notificationHeader: 'Notifications',
      privacyHeader: 'Privacy Settings',
      followersListHeader: 'Allow others to see my followers -',
      followingsListHeader: 'Allow others to see my following -',
    },
    permission: {
      perm_Headline_1: `Don't Miss Out`,
      perm_Headline_2: `Need your Permission to work`,
      permission_1: 'Storage Access',
      permission_2: 'Camera Access',
      permission_3: 'Mic Access',
      permission_4: 'Location Access',
      deny: `I'm not Ready`,
      access: 'Allow Access',
      error: 'Error !!',
      message: 'Permission Required'
    },
    uploading: {
      album: 'Album is uploading...',
      title: 'Error!!',
      logout: `Can't logout! Please wait until Album uploading is completed`
    },
    copyRight: '© 2021 MyZesty Inc. a Beyond Apps Group company',
    copyRightHead: '© 2021 MyZesty Inc.  a ',
    copyrightMid: `Beyond Apps Group`,
    copyRighttail: ' company',
    shareMessage: 'To check the full album. Please click here: ',
    Intro: {
      h1: 'Get started!',
      h1_2: 'Free, during the promotional period',
      h2: 'To get full access to all available amazing tools!',
      skipBtn: 'Skip',
      signup: 'Create an Account',
      login: 'login',
      loginText: ' if you already have an account',
      done: 'Done',
      back: 'Back',
      try: 'Try It Now',
    },
    'Water Mark': `Adding watermark to your pictures to show who and where it was from, in case it was copied from.`,
    'Allow Collab': `Allow others to collaborate with you to build the album. Your friends will be allowed to add more images to your album. For example, if you share a trip together, everybody can collaborate to build this album.`,
    noImageError: 'No Images/Videos Selected !!',
    trimVideoError: 'Please trim video first',
    accountSuspendedError: 'Your account has suspended, Please contact with support!',
    profileError: 'Profile Not Found!!',
    reportUser: {
      heading: 'Report User',
      placeholder: 'Write your reason..',
      text_1: 'Fake Account',
      text_2: 'Posting Inappropriate Things',
      text_3: 'Copyright violence',
      text_4: 'Harassment or Bullying',
      text_5: 'Others',
      success: 'Success',
      error: 'Error !!',
      successMessage: 'Report has been sent. Thanks',
      errorMessage: 'You already reported this user.'
    },
    resetPassword: 'Reset Your Password'
  };
  